# -*- coding: utf-8 -*-
"""final_gps_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d7t5XvB0CvcGDi3M1zz0eadO_nfOMuN
"""

#!/usr/bin/env python3
# main.py - GPS -> ANFIS -> fuzzy fallback -> decision + CSV logger
#
# Requirements:
#   pip install pyserial pynmea2 numpy torch scikit-fuzzy pandas

import time
import json
import math
import csv
import sys
from pathlib import Path
from collections import deque

import numpy as np
import torch
import torch.nn as nn
import pynmea2
import serial

# -----------------------------
# USER CONFIG
# -----------------------------
SERIAL_PORT = "/dev/serial0"      # or "/dev/ttyAMA0"
BAUD_RATE = 9600
MODEL_PATH = "anfis_v3.pth"
META_PATH = "anfis_v3_meta.json"
CSV_LOG = "realtime_log.csv"
ANFIS_SIMILARITY_THRESHOLD = 3.0   # Mahalanobis-like threshold (tune)
VIBRATION_WINDOW = 8              # number of recent jumps to compute 'vibration_x'
DEVICE = "cpu"
# -----------------------------
recent_jumps = deque(maxlen=10)  # for vibration calculation
last_lat, last_lon, last_time = None, None, None

# -----------------------------
# Utilities
# -----------------------------
def haversine_m(lat1, lon1, lat2, lon2):
    # meters
    R = 6371000.0
    phi1 = math.radians(lat1); phi2 = math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi/2.0)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2.0)**2
    return 2*R*math.atan2(math.sqrt(a), math.sqrt(1-a))

def now_ts():
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

# -----------------------------
# ANFIS model class used for training (must match saved model)
# This matches the ANFIS class used earlier: mf_x1..mf_x3 and 'consequents'
# -----------------------------
class GaussianMF(nn.Module):
    def __init__(self, mean: float, sigma: float):
        super().__init__()
        self.mean = nn.Parameter(torch.tensor(float(mean)))
        # parameterize sigma via log to ensure positive
        self.log_sigma = nn.Parameter(torch.tensor(float(np.log(max(sigma, 1e-6)))))

    def forward(self, x):
        sigma = torch.exp(self.log_sigma)
        return torch.exp(-0.5 * ((x - self.mean) / sigma).pow(2.0))

class ANFIS_3in_1out(nn.Module):
    def __init__(self, n_mfs: int = 3):
        super().__init__()
        self.n_mfs = n_mfs
        self.n_rules = n_mfs ** 3
        # ModuleLists of Gaussian MFs (as used in your training script)
        self.mf_x1 = nn.ModuleList([GaussianMF(np.random.uniform(-1,1), np.random.uniform(0.1,1.0)) for _ in range(n_mfs)])
        self.mf_x2 = nn.ModuleList([GaussianMF(np.random.uniform(-1,1), np.random.uniform(0.1,1.0)) for _ in range(n_mfs)])
        self.mf_x3 = nn.ModuleList([GaussianMF(np.random.uniform(-1,1), np.random.uniform(0.1,1.0)) for _ in range(n_mfs)])
        # consequents: [n_rules, 4] -> a1, a2, a3, b
        self.consequents = nn.Parameter(torch.randn(self.n_rules, 4) * 0.1)

    def forward(self, x):
        # x shape [B, 3]
        x1, x2, x3 = x[:,0], x[:,1], x[:,2]
        m1 = torch.stack([mf(x1) for mf in self.mf_x1], dim=1)  # [B, n_mfs]
        m2 = torch.stack([mf(x2) for mf in self.mf_x2], dim=1)
        m3 = torch.stack([mf(x3) for mf in self.mf_x3], dim=1)

        B = x.shape[0]
        rules = torch.zeros(B, self.n_rules, device=x.device)
        idx = 0
        for i in range(self.n_mfs):
            for j in range(self.n_mfs):
                for k in range(self.n_mfs):
                    rules[:, idx] = m1[:, i] * m2[:, j] * m3[:, k]
                    idx += 1
        denom = rules.sum(dim=1, keepdim=True) + 1e-9
        w_norm = rules / denom  # [B, n_rules]

        a = self.consequents  # [n_rules, 4]
        # compute per-rule linear output: a1*x1 + a2*x2 + a3*x3 + b
        x1e = x1.unsqueeze(1); x2e = x2.unsqueeze(1); x3e = x3.unsqueeze(1)
        y_rule = a[:,0].unsqueeze(0)*x1e + a[:,1].unsqueeze(0)*x2e + a[:,2].unsqueeze(0)*x3e + a[:,3].unsqueeze(0)
        y = (w_norm * y_rule).sum(dim=1)
        return y   # raw scalar (no sigmoid)

# -----------------------------
# Fuzzy fallback engine (scikit-fuzzy)
# -----------------------------
# We'll build a compact rule engine using skfuzzy.control
try:
    import skfuzzy as fuzz
    from skfuzzy import control as ctrl
    SKFUZZY_AVAILABLE = True
except Exception:
    SKFUZZY_AVAILABLE = False

def build_fuzzy_engine():
    """Return a ControlSystemSimulation object (3-input -> 1 output)."""
    if not SKFUZZY_AVAILABLE:
        return None
    satellites = ctrl.Antecedent(np.arange(0, 21, 1), 'satellites')
    hdop = ctrl.Antecedent(np.arange(0, 21, 0.1), 'hdop')
    jump = ctrl.Antecedent(np.arange(0, 101, 1), 'jump')  # meters
    trust = ctrl.Consequent(np.arange(0, 1.01, 0.01), 'trust')

    satellites['FEW'] = fuzz.trimf(satellites.universe, [0,0,6])
    satellites['OKAY'] = fuzz.trimf(satellites.universe, [4,8,12])
    satellites['MANY'] = fuzz.trimf(satellites.universe, [10,20,20])

    hdop['EXCELLENT'] = fuzz.trimf(hdop.universe, [0,0.8,1.5])
    hdop['GOOD'] = fuzz.trimf(hdop.universe, [1.2,2.0,3])
    hdop['POOR'] = fuzz.trimf(hdop.universe, [2.5, 21, 21])

    jump['NORMAL'] = fuzz.trimf(jump.universe, [0,0,5])
    jump['SUSPICIOUS'] = fuzz.trimf(jump.universe, [4,10,30])
    jump['IMPOSSIBLE'] = fuzz.trimf(jump.universe, [20,100,100])

    trust['LOW'] = fuzz.trimf(trust.universe, [0,0,0.45])
    trust['MEDIUM'] = fuzz.trimf(trust.universe, [0.35,0.6,0.8])
    trust['HIGH'] = fuzz.trimf(trust.universe, [0.7,1,1])

    rules = [
        ctrl.Rule(satellites['FEW'] | hdop['POOR'], trust['LOW']),
        ctrl.Rule(jump['IMPOSSIBLE'], trust['LOW']),
        ctrl.Rule(satellites['OKAY'] & hdop['GOOD'] & jump['NORMAL'], trust['MEDIUM']),
        ctrl.Rule(satellites['MANY'] & hdop['EXCELLENT'] & jump['NORMAL'], trust['HIGH']),
    ]
    cs = ctrl.ControlSystem(rules)
    sim = ctrl.ControlSystemSimulation(cs)
    return sim

# -----------------------------
# Load ANFIS model robustly
# -----------------------------
def load_anfis_model(model_path: str, meta_path: str, device="cpu"):
    # read meta
    meta = {}
    if Path(meta_path).exists():
        with open(meta_path, "r") as f:
            meta = json.load(f)
    else:
        print(f"[WARN] meta file {meta_path} not found. continuing with defaults.")

    # try find n_mfs
    n_mfs = meta.get("n_mfs")
    # if not in meta, try infer from checkpoint keys
    if n_mfs is None and Path(model_path).exists():
        # load state keys only
        sd = torch.load(model_path, map_location="cpu")
        # count mf_x1.* keys
        keys = list(sd.keys())
        # pattern 'mf_x1.{i}.mean' or 'mf_x1.{i}.mean' depending on training
        count = 0
        for k in keys:
            if k.startswith("mf_x1.") and ".mean" in k:
                # extract index
                count += 1
        if count > 0:
            n_mfs = count
    if n_mfs is None:
        n_mfs = meta.get("mu") and 3 or 3  # fallback 3

    print(f"[INFO] Using n_mfs = {n_mfs}")

    # construct model and attempt to load
    model = ANFIS_3in_1out(n_mfs=n_mfs)
    try:
        state = torch.load(model_path, map_location=device)
        # if it's state_dict, try to load
        if isinstance(state, dict) and all(k.startswith("mf_x1") or k.startswith("mf_x2") or k.startswith("mf_x3") or k.startswith("consequents") for k in state.keys()):
            model.load_state_dict(state)
        else:
            # maybe saved model.state_dict() or entire module - try both
            try:
                model.load_state_dict(state)
            except Exception:
                # maybe user saved a model object, attempt to load and extract state_dict
                temp = state
                if hasattr(temp, "state_dict"):
                    sd = temp.state_dict()
                    model.load_state_dict(sd)
                else:
                    raise
        print("[INFO] ANFIS model loaded.")
    except Exception as e:
        print("[ERROR] Could not load ANFIS model cleanly:", e)
        return None, meta

    return model, meta

# -----------------------------
# ANFIS similarity test
# -----------------------------
def is_similar_to_training(x_raw: np.ndarray, mu: np.ndarray, sigma: np.ndarray, threshold=ANFIS_SIMILARITY_THRESHOLD):
    # Mahalanobis-like distance using diag(sigma)
    diff = (x_raw - mu)
    # avoid zero sigma
    sig = np.copy(sigma); sig[sig==0] = 1.0
    dist = np.sqrt(np.sum((diff / sig) ** 2))
    return float(dist), (dist <= threshold)

# -----------------------------
# Scenario mapping
# -----------------------------
def map_score_to_label(score: float):
    if score >= 0.75:
        return "GOOD"
    if score >= 0.45:
        return "JAMMED/WEAK"
    return "SPOOFED"

# -----------------------------
# CSV header create if missing
# -----------------------------
def ensure_csv_header(path):
    header = ["timestamp","speed_m_s","num_sats","alt_m","hdop","vibration_x","anfis_score","fuzzy_score","final_score","final_decision","scenario"]
    p = Path(path)
    if not p.exists():
        with open(p, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(header)

# -----------------------------
# Main realtime loop
# -----------------------------
def main():
    print("Starting pipeline: GPS -> ANFIS -> fuzzy fallback -> logger")
    print("[INFO] Listening for NMEA on /dev/serial0 @ 9600 ... Press Ctrl-C to stop.")

    while True:
        # --- read GPS line & parse ---
        line = read_gps_line()  # your function to read NMEA
        parsed = parse_nmea(line)  # returns dict: lat, lon, sats, hdop, valid_fix

        lat = parsed.get('lat')
        lon = parsed.get('lon')
        sats = parsed.get('sats', 0)
        hdop = parsed.get('hdop')
        valid_fix = parsed.get('valid_fix', False)

        # --- skip invalid / zero-satellite readings ---
        if not valid_fix or sats == 0 or hdop is None or hdop > 50:
            continue  # silently ignore, do not print/log

        # --- compute jump & vibration ---
        tnow = time.time()
        jump_m = 0.0
        if last_lat is not None:
            dt = max(1e-6, tnow - last_time)
            jump_m = haversine_m(last_lat, last_lon, lat, lon)
        last_lat, last_lon, last_time = lat, lon, tnow

        recent_jumps.append(jump_m)
        vib_x = float(np.std(list(recent_jumps))) if recent_jumps else 0.0

        # --- ANFIS prediction ---
        try:
            raw_input = np.array([hdop, float(sats), vib_x], dtype=float)
            anfis_output = float(anfis_model.predict(raw_input))
            anfis_output = np.clip(anfis_output, 0.0, 1.0)
        except Exception:
            anfis_output = 0.0

        # --- Fuzzy fallback ---
        try:
            fuzzy_input = {
                'hdop': hdop,
                'sats': float(sats),
                'vib': vib_x
            }
            fuzzy_output = float(fuzzy_system.compute(fuzzy_input))
            fuzzy_output = np.clip(fuzzy_output, 0.0, 1.0)
        except Exception:
            fuzzy_output = 0.0

        # --- final decision ---
        if anfis_output > 0.0:
            final_score = anfis_output
            status = get_status_from_score(final_score, method="ANFIS")
        else:
            final_score = fuzzy_output
            status = get_status_from_score(final_score, method="FUZZY_FALLBACK")

        # --- print/log ---
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        output_str = (f"[{timestamp}] Lat:{lat:.6f} Lon:{lon:.6f} sats:{sats} "
                      f"hdop:{hdop:.2f} jump:{jump_m:.2f}m vib:{vib_x:.2f} "
                      f"anfis:{anfis_output:.3f} fuzzy:{fuzzy_output:.3f} "
                      f"final:{final_score:.3f} => {status}")
        print(output_str)

        # --- append to CSV ---
        with open("gps_log.csv", "a", newline='') as fcsv:
            writer = csv.writer(fcsv)
            writer.writerow([timestamp, lat, lon, sats, hdop, jump_m, vib_x,
                             anfis_output, fuzzy_output, final_score, status])

        time.sleep(0.5)  # adjust loop rate as needed
if __name__ == "__main__":
    main()
