# -*- coding: utf-8 -*-
"""fuzzy_engine.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyF8h-SXlZ8AJS90TbRjW7zZY-D_svrt
"""

# fuzzy_engine.py
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# --- Inputs (Antecedents) ---
satellites = ctrl.Antecedent(np.arange(0, 16, 1), 'satellites')
hdop = ctrl.Antecedent(np.arange(1, 11, 0.1), 'hdop')
consistency = ctrl.Antecedent(np.arange(0, 51, 1), 'consistency')
vibration = ctrl.Antecedent(np.arange(0, 51, 1), 'vibration')
# NEW INPUT for barometer cross-validation
baro_gps_discrepancy = ctrl.Antecedent(np.arange(0, 51, 1), 'baro_gps_discrepancy')

# --- Output (Consequent) ---
gps_trust = ctrl.Consequent(np.arange(0, 1.01, 0.01), 'gps_trust_score')

# --- Membership Functions ---
satellites['FEW'] = fuzz.trimf(satellites.universe, [0, 0, 5])
satellites['OKAY'] = fuzz.trimf(satellites.universe, [4, 7, 10])
satellites['MANY'] = fuzz.trimf(satellites.universe, [8, 15, 15])

hdop['EXCELLENT'] = fuzz.trimf(hdop.universe, [1, 1, 1.5])
hdop['GOOD'] = fuzz.trimf(hdop.universe, [1.4, 2, 3])
hdop['POOR'] = fuzz.trimf(hdop.universe, [2.5, 10, 10])

consistency['SMOOTH'] = fuzz.trimf(consistency.universe, [0, 0, 15])
consistency['JUMPY'] = fuzz.trimf(consistency.universe, [10, 25, 40])
consistency['ERRATIC'] = fuzz.trimf(consistency.universe, [35, 50, 50])

vibration['LOW'] = fuzz.trimf(vibration.universe, [0, 0, 10])
vibration['MEDIUM'] = fuzz.trimf(vibration.universe, [5, 15, 25])
vibration['HIGH'] = fuzz.trimf(vibration.universe, [20, 50, 50])

# NEW Membership Function for Barometer Discrepancy
baro_gps_discrepancy['LOW'] = fuzz.trimf(baro_gps_discrepancy.universe, [0, 0, 10]) # 0-10 meter difference is acceptable
baro_gps_discrepancy['HIGH'] = fuzz.trimf(baro_gps_discrepancy.universe, [5, 50, 50]) # 5+ meter difference is a problem

# For the output Trust Score
gps_trust['VERY_LOW'] = fuzz.trimf(gps_trust.universe, [0, 0, 0.25])
gps_trust['LOW'] = fuzz.trimf(gps_trust.universe, [0.15, 0.35, 0.55])
gps_trust['MEDIUM'] = fuzz.trimf(gps_trust.universe, [0.45, 0.6, 0.75])
gps_trust['HIGH'] = fuzz.trimf(gps_trust.universe, [0.65, 0.8, 0.9])
gps_trust['VERY_HIGH'] = fuzz.trimf(gps_trust.universe, [0.85, 1, 1])

# --- Rulebook with Full Fusion Logic ---
# High-priority rules for immediate distrust
rule1 = ctrl.Rule(satellites['FEW'] | hdop['POOR'], gps_trust['LOW'])
rule2 = ctrl.Rule(consistency['ERRATIC'], gps_trust['VERY_LOW'])
rule3 = ctrl.Rule(vibration['HIGH'], gps_trust['VERY_LOW'])
rule4_baro = ctrl.Rule(baro_gps_discrepancy['HIGH'], gps_trust['VERY_LOW']) # NEW RULE

# Rules for nominal to high trust conditions
rule5 = ctrl.Rule(consistency['JUMPY'], gps_trust['LOW'])
rule6 = ctrl.Rule(satellites['OKAY'] & hdop['GOOD'] & consistency['SMOOTH'] & vibration['LOW'] & baro_gps_discrepancy['LOW'], gps_trust['HIGH'])
rule7 = ctrl.Rule(satellites['MANY'] & hdop['EXCELLENT'] & consistency['SMOOTH'] & vibration['LOW'] & baro_gps_discrepancy['LOW'], gps_trust['VERY_HIGH'])
rule8 = ctrl.Rule(satellites['OKAY'] & hdop['GOOD'] & vibration['MEDIUM'], gps_trust['MEDIUM'])

# Create the Control System
gps_ctrl_system = ctrl.ControlSystem([rule1, rule2, rule3, rule4_baro, rule5, rule6, rule7, rule8])
gps_simulator = ctrl.ControlSystemSimulation(gps_ctrl_system)