# -*- coding: utf-8 -*-
"""generate_dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oODUTDMd0Pd8JC23pZup2XhwYAquvve1
"""

import time
import csv
import random
import numpy as np
from fuzzy_engine import gps_simulator

# --- Configuration ---
LOG_FILE = 'supervisor_log.csv'
LOG_HEADER = [
    "timestamp", "satellites", "hdop", "vibration_x",
    "gps_trust_score", "action_taken", "scenario"
]

def run_logic_and_log(writer, scenario_name, data):
    """A helper function to run the fuzzy logic and write a log entry."""
    # Run the fuzzy logic simulation
    trust_score = 0.1 # Default to low trust
    try:
        jump = 0
        alt_discrepancy = data.get("baro_gps_discrepancy", 0.0)
        gps_simulator.input['satellites'] = data["satellites"]
        gps_simulator.input['hdop'] = data["hdop"]
        gps_simulator.input['consistency'] = jump
        gps_simulator.input['vibration'] = data["vibration_x"]
        gps_simulator.input['baro_gps_discrepancy'] = alt_discrepancy
        gps_simulator.compute()
        trust_score = gps_simulator.output['gps_trust_score']
    except Exception as e:
        print(f"Fuzzy logic error: {e}")

    # Determine action and create log entry
    action_taken = "FAILSAFE" if trust_score < 0.5 else "Nominal"
    current_time = time.strftime("%Y-%m-%d %H:%M:%S")
    log_data = [
        current_time, data["satellites"], f"{data['hdop']:.2f}", f"{data['vibration_x']:.2f}",
        f"{trust_score:.2f}", action_taken, scenario_name
    ]
    writer.writerow(log_data)

def generate_normal_data(writer, num_points):
    """Generates data points for normal, healthy flight."""
    print(f"Generating {num_points} 'Normal' data points...")
    for _ in range(num_points):
        data = {
            "satellites": random.randint(12, 15),
            "hdop": random.uniform(1.0, 1.6),
            "vibration_x": random.uniform(2, 8)
        }
        run_logic_and_log(writer, "Normal", data)

def simulate_jamming_attack(writer, duration_steps):
    """Simulates a jamming attack where satellite count drops over time."""
    print(f"Simulating a 'Jamming Attack' over {duration_steps} steps...")
    sats_decline = np.linspace(14, 2, duration_steps)
    hdop_increase = np.linspace(1.5, 9.0, duration_steps)
    for i in range(duration_steps):
        data = {
            "satellites": int(sats_decline[i]),
            "hdop": hdop_increase[i] + random.uniform(-0.5, 0.5),
            "vibration_x": random.uniform(4, 6)
        }
        run_logic_and_log(writer, "Jamming Attack", data)

def simulate_spoofing_drift(writer, duration_steps):
    """Simulates a spoofing attack by creating a growing altitude discrepancy."""
    print(f"Simulating a 'Spoofing Drift' attack over {duration_steps} steps...")
    discrepancy_increase = np.linspace(0, 40, duration_steps) # Discrepancy grows to 40m
    for i in range(duration_steps):
        data = {
            "satellites": 15, # GPS signal looks perfect
            "hdop": 1.1,
            "vibration_x": random.uniform(4, 6),
            "baro_gps_discrepancy": discrepancy_increase[i] + random.uniform(-1, 1)
        }
        run_logic_and_log(writer, "Spoofing Attack", data)

def main():
    """Main function to orchestrate dataset generation."""
    with open(LOG_FILE, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(LOG_HEADER)
        print(f"--- Starting Advanced Dataset Generation. Saving to '{LOG_FILE}' ---")

        # You can customize your dataset by changing these numbers
        generate_normal_data(writer, 1000)
        simulate_jamming_attack(writer, 100)
        generate_normal_data(writer, 2000) # Some normal data between attacks
        simulate_spoofing_drift(writer, 500)
        generate_normal_data(writer, 1500)

        print("\n--- Dataset generation complete. ---")

if __name__ == "__main__":
    main()