# -*- coding: utf-8 -*-
"""live_supervisor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tv5ZLo9yrhY4NuBoSUbjAMzje2pj-ih
"""

# live_supervisor.py
import time
import csv
from pymavlink import mavutil
from fuzzy_engine import gps_simulator

# --- Configuration ---
CONNECTION_PORT = '/dev/serial0'
BAUD_RATE = 57600
LOG_FILE = 'live_flight_log.csv'
LOG_HEADER = [
    "timestamp", "satellites", "hdop", "vibration_x", "gps_altitude_m", "baro_altitude_m",
    "altitude_discrepancy_m", "gps_trust_score", "action_taken"
]

def connect_to_vehicle():
    """Establishes a MAVLink connection to the drone."""
    print(f"Connecting to vehicle on: {CONNECTION_PORT} at {BAUD_RATE} baud")
    vehicle = mavutil.mavlink_connection(CONNECTION_PORT, baud=BAUD_RATE)
    print("Waiting for heartbeat...")
    vehicle.wait_heartbeat()
    print("Heartbeat received! Vehicle is connected.")
    return vehicle

def request_data_streams(vehicle):
    """Requests necessary MAVLink data streams from the flight controller."""
    for msg_id, freq in [
        (mavutil.mavlink.MAVLINK_MSG_ID_GPS_RAW_INT, 2),
        (mavutil.mavlink.MAVLINK_MSG_ID_VIBRATION, 2),
        (mavutil.mavlink.MAVLINK_MSG_ID_GLOBAL_POSITION_INT, 2),
        (mavutil.mavlink.MAVLINK_MSG_ID_SCALED_PRESSURE2, 2)
    ]:
        vehicle.mav.command_long_send(
            vehicle.target_system, vehicle.target_component,
            mavutil.mavlink.MAV_CMD_SET_MESSAGE_INTERVAL, 0,
            msg_id, 1e6 / freq, 0, 0, 0, 0, 0)

def run_supervisor(vehicle):
    """The main live supervisor loop."""
    print("\n--- Supervisor is LIVE ---")

    with open(LOG_FILE, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(LOG_HEADER)
        print(f"Logging live data to '{LOG_FILE}'...")

        latest_data = {
            "sats": 0, "hdop": 9.9, "vibration_x": 0.0,
            "gps_altitude": None, "baro_altitude": None
        }

        try:
            while True:
                msg = vehicle.recv_match(
                    type=['GPS_RAW_INT', 'VIBRATION', 'GLOBAL_POSITION_INT', 'SCALED_PRESSURE2'],
                    blocking=True, timeout=1.0)

                if not msg:
                    print("No data received in last second.")
                    continue

                msg_type = msg.get_type()
                if msg_type == 'GPS_RAW_INT':
                    latest_data["sats"] = msg.satellites_visible
                    latest_data["hdop"] = msg.eph / 100.0 if msg.eph != 65535 else 9.9
                elif msg_type == 'VIBRATION':
                    latest_data["vibration_x"] = msg.vibration_x
                elif msg_type == 'GLOBAL_POSITION_INT':
                    latest_data["gps_altitude"] = msg.alt / 1000.0
                elif msg_type == 'SCALED_PRESSURE2':
                    latest_data["baro_altitude"] = msg.alt

                alt_discrepancy = 0.0
                if latest_data["gps_altitude"] is not None and latest_data["baro_altitude"] is not None:
                    alt_discrepancy = abs(latest_data["gps_altitude"] - latest_data["baro_altitude"])

                try:
                    jump = 0
                    gps_simulator.input['satellites'] = latest_data["sats"]
                    gps_simulator.input['hdop'] = latest_data["hdop"]
                    gps_simulator.input['consistency'] = jump
                    gps_simulator.input['vibration'] = latest_data["vibration_x"]
                    gps_simulator.input['baro_gps_discrepancy'] = alt_discrepancy

                    gps_simulator.compute()
                    trust_score = gps_simulator.output['gps_trust_score']
                except Exception as e:
                    print(f"FUZZY LOGIC ERROR: {e}. Defaulting to low trust.")
                    trust_score = 0.1

                action_taken = "Nominal"
                trust_threshold = 0.5
                if trust_score < trust_threshold:
                    action_taken = "FAILSAFE: LAND command sent"
                    print(f"ALERT: Trust Low ({trust_score:.2f}). Triggering Failsafe.")
                    vehicle.mav.command_long_send(
                        vehicle.target_system, vehicle.target_component,
                        mavutil.mavlink.MAV_CMD_DO_SET_MODE,
                        0, 1, 9, 0, 0, 0, 0, 0)

                current_time = time.strftime("%Y-%m-%d %H:%M:%S")
                log_data = [
                    current_time, latest_data["sats"], latest_data["hdop"], latest_data["vibration_x"],
                    latest_data["gps_altitude"], latest_data["baro_altitude"], f"{alt_discrepancy:.2f}",
                    f"{trust_score:.2f}", action_taken
                ]
                writer.writerow(log_data)
                f.flush()
                print(f"LOGGED: {log_data}")

        except KeyboardInterrupt:
            print("\nSupervisor shutting down.")
        finally:
            vehicle.close()

if __name__ == "__main__":
    try:
        drone_vehicle = connect_to_vehicle()
        if drone_vehicle:
            request_data_streams(drone_vehicle)
            run_supervisor(drone_vehicle)
    except Exception as e:
        print(f"Error starting supervisor: {e}")