# -*- coding: utf-8 -*-
"""train_anfis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkus096eqyjsvoWi6iNz6Rax64IpddYU
"""

import pandas as pd
import numpy as np
import torch
import anfis
from anfis.membership import GaussMf, BellMf, SigmoidMf
import pickle

# --- Configuration ---
LABELED_DATA_FILE = 'final_labeled_dataset.csv'
MODEL_OUTPUT_FILE = 'anfis_model.pkl'
EPOCHS = 100 # Number of training cycles

def prepare_data(filename):
    """Loads the labeled CSV and prepares data for training."""
    print(f"Loading labeled data from '{filename}'...")
    df = pd.read_csv(filename)

    # Define your input features and the target output
    input_columns = ['satellites', 'hdop', 'vibration_x']
    output_column = 'target_trust_score'

    # Convert data to PyTorch tensors
    X = torch.from_numpy(df[input_columns].values).float()
    Y = torch.from_numpy(df[output_column].values).float()

    return X, Y

def train_anfis_model(X_train, Y_train):
    """Defines, trains, and returns an ANFIS model."""
    # Define the ANFIS model structure
    # This defines 3 inputs, each with 3 Gaussian membership functions
    membership_functions = [
        ('satellites', GaussMf(np.array([-2., 8., 18.]), np.array([4., 4., 4.]))),
        ('hdop', GaussMf(np.array([-2., 5.5, 13.]), np.array([3., 3., 3.]))),
        ('vibration', GaussMf(np.array([-10., 25., 60.]), np.array([10., 10., 10.])))
    ]
    model = anfis.AnfisNet(membership_functions)

    # Define the optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)

    print("--- Starting ANFIS Training ---")
    for epoch in range(EPOCHS):
        # Make a prediction
        Y_pred = model(X_train)

        # Calculate loss (Mean Squared Error)
        loss = torch.nn.functional.mse_loss(Y_pred.squeeze(), Y_train)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {loss.item():.4f}")

    print("--- Training Complete ---")
    return model

if __name__ == "__main__":
    # 1. Prepare the data
    X, Y = prepare_data(LABELED_DATA_FILE)

    # 2. Train the model
    trained_model = train_anfis_model(X, Y)

    # 3. Save the trained model for later use
    print(f"Saving trained model to '{MODEL_OUTPUT_FILE}'...")
    with open(MODEL_OUTPUT_FILE, 'wb') as f:
        pickle.dump(trained_model, f)

    print("Model saved successfully.")