# -*- coding: utf-8 -*-
"""launcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSmCMPHAExgCcphbBliNF-y0HqCHV0ja
"""

import hashlib
import subprocess
import os

# --- CONFIGURATION ---
SCRIPT_TO_RUN = "main_supervisor.py"
KNOWN_GOOD_HASH = "2d6ac3bcf159f47076a38b969cf83553737b0a6d470d68f9798ae6139d39d073"

# --- Get the absolute path to the script ---
# This ensures the script is found, even when run with sudo
script_dir = os.path.dirname(os.path.abspath(__file__))
script_path = os.path.join(script_dir, SCRIPT_TO_RUN)


def get_file_hash(filename):
    """Calculates the SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    try:
        with open(filename, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except FileNotFoundError:
        return None

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    print("--- Secure Launcher Initialized ---")

    print(f"Verifying integrity of '{script_path}'...")
    current_hash = get_file_hash(script_path)

    if current_hash is None:
        print(f"ERROR: The script '{SCRIPT_TO_RUN}' was not found at '{script_path}'.")

    elif current_hash == KNOWN_GOOD_HASH:
        print("Integrity OK. Starting supervisor...")
        # Run the main script using its full path
        subprocess.run(["sudo", "python3", script_path])

    else:
        print("\n" + "="*50)
        print("!!! CRITICAL SECURITY ALERT !!!")
        print(f"The script '{SCRIPT_TO_RUN}' has been modified or tampered with!")
        print("Execution halted for safety.")
